### ISSUE TITLE
audit --status-code filter does not work

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-lib#78]
Error: [POST /v1/audit/find][500] findAuditTraces default  unaccepted status code found: 400 expected: [200], MeilisearchApiError Message: Inside `.queries[0]`: Attribute `status-code` is not filterable. Available filterable attributes are: `path body component user timestamp-unix detail tenant phase rqid remote-addr type forwarded-for`.
1:12 status-code = 500, Code: invalid_search_filter, Type: invalid_request, Link: https://docs.meilisearch.com/errors#invalid_search_filter (path "POST /multi-search" with method "MultiSearch") (500)

**Comment by vknabel** [comment]
Was fixed in #80
